# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 87b5fb51c4b2424641b14cea68a0c415fb778eb6342940bfc2fe4f4cf2d3782402ee13bb392a224accecf0bf652e4ab307726d1f7ad45f6ec0680218c8d76a32

test:
  secret_key_base: 24901793dfee268e247e1008a0f50fa45c9b50f7ebbfc3967adb9f585111d39c4790ef81e97cd547c08236568237aa326128bbaba0cb9a32bfdf28ca0dc76c86

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
